FROM ubuntu:18.04
LABEL maintainer="Amne a aprendiz"
RUN apt-get update && apt-get install curl nginx -y && rm -rf /var/lib/apt/lists/*
EXPOSE 80
ADD lombok.tar.gz /root/lombok
COPY index.html /var/www/html/
WORKDIR /var/www/html
ENV APP_VERSION 1.0.0
ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]
HEALTHCHECK --timeout=2s CMD curl localhost || exit 1
